theme: jekyll-theme-cayman
title: Diagnosis and Early Detection of Alzheimer's through Gene Expression
description: For some patients, gene expression tests, particularly for a small number of targeted genes, may be relatively inexpensive and less invasive compared to traditional methods such as radiolabeled PET scans.
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
